{
 "title": "Bitcoin",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Price", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BTC - USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket:\"Crypto\")\n  |> range(start: -1d)\n  |> filter(fn: (r) =>\n    r._measurement == \"BTC\")\n  |> filter(fn:(r) => r._field == \"Price\" )\n  |> yield()"
    }
   ]
  },
  {
   "title": "BTC - USD",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"Crypto\")\n  |> range(start: -1d)\n  |> filter(fn: (r) =>\n    r._measurement == \"BTC\"\n  )\n  |> filter(fn:(r) => r._field == \"Price\" )\n  |> yield()"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Blockcount",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"Crypto\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"BTC\")\n  |> filter(fn:(r) => r._field == \"BlockCount\" )\n  |> yield()"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "datasoure": { "type": "influxdb", "uid": "${DS_INFLUXDB}" },
     "query": "from(bucket:\"Crypto\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"BTC\")\n  |> filter(fn:(r) => r._field == \"Difficulty\" )\n  |> yield()"
    }
   ]
  }
 ]
}